### PR TITLE
Tornado

### PR DESCRIPTION
**Pull request by csgamble**
This adds the requirements. Git is stressful.

### CODE REVIEW

**Comment by csgamble** [comment]
The only thing the documentation says for `self.finish()` is that it "ends the HTTP request", which is good, but I wonder if it would still need the same JSON workaround.

**Comment by nnieman** [comment]
Yep, on the `self.finish` thing, we will still need the JSON workaround.
Your updated comments look good!

**Comment by csgamble** [comment]
Updated the file to switch to `self.finish()`. Is everything Gucci now?

**Comment by nnieman** [comment]
Yep, looks good!

**Pull request merged**
